### ISSUE TITLE
Sorting discussion on last post

### ISSUE THREAD

**Issue by demobiel** [thedevdojo/chatter#102]
Hi!

thank you for the package it is really nice!

I try to change the sort order of the discussions on the homepage by showing the discussion with the most recent post on top.

At the moment I am trying to modify the ChatterController where you have this line:

`$discussions = Models::discussion()->with('user')->with('post')->with('postsCount')->with('category')->orderBy('created_at', 'DESC')->paginate($pagination_results);
`
Here I would like to change the orderBy to point to the related posts. I tried with joins, which indeed makes them sort how I want them to sort, but at that moment the relation "post" in the discussion model is no longer populated.

I tried the following:

```
        $discussions = Models::discussion()->with('user')->with('post')->with('postsCount')->with('category')
            ->leftJoin('chatter_post','chatter_discussion.id','=','chatter_post.chatter_discussion_id')
            ->groupBy(['chatter_discussion.id'])
            ->orderByRaw('max(chatter_post.created_at) desc')
            ->paginate($pagination_results);

```
But this gives error with the groupBy clause.

I know this is not the spot to ask for stuff, but I don't know where to go elsewhere.

If you would be so kind to answer, if not I understand as well.

Thanks!

**Comment by marktopper** [comment]
This is now possible with the latest version. [View config](https://github.com/thedevdojo/chatter/blob/master/config/chatter.php#L208).

**Comment by demobiel** [comment]
thanks!!
