### ISSUE TITLE
delete discussion and search discussion option

### ISSUE THREAD

**Issue by amirgee007** [thedevdojo/chatter#106]
hi is there any module in this package to delete the discussion if admin feel its dirty or something else.

also if i want to search any discussion is there any way to search??

https://packagist.org/packages/flarum/flarum

like this search discussion, i used it but i thing its not good for me.

please can you add the search box in this package just a suggestion

**Comment by Chinese1904** [comment]
I agree it would be a nice feature, but not sure if any of the people that develop here are interested in developing it. I am not in big use for it personally yet

https://github.com/thedevdojo/chatter/issues/23

**Comment by amirgee007** [comment]
ok no problem.

thanks
