### ISSUE TITLE
table errors

### ISSUE THREAD

**Issue by iiCe89** [thedevdojo/chatter#11]
i followed your instructions word for word - but getting this error

SQLSTATE[HY000]: General error: 1 table chatter_discussion has no column named slug (SQL: insert into "chatter_discussion" ("title", "chatter_category_id", "user_id", "slug", "color", "updated_at", "created_at") values (Hello, 2, 1, hello, #b6d40d, 2016-09-19 11:20:27, 2016-09-19 11:20:27)

**Comment by JayLancaster** [comment]
Have you run the seeder?
  php artisan db:seed --class=ChatterTableSeeder

**Comment by iiCe89** [comment]
yes still getting errors

**Comment by iiCe89** [comment]
fixed

**Comment by JayLancaster** [comment]
It might be adviseable to post your solution here for other potential users of chatter 👍
