### ISSUE TITLE
No CSS and JS yield are working

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/chatter#124]
I am using Laravel 5.4. And I completed all steps given to install chatter. But its still not working.

**Comment by putheakhem** [comment]
@MohsinNadeem  I already working with laravel 5.4. it's worked fine. Please give us any error message. Please check that you include yield in the correct place

**Comment by Naveed-anwar123** [comment]
I have same problem. No css and js files in forums url.

**Comment by putheakhem** [comment]
@Naveed-anwar123  you can check again . Here 
 http://putheakhem.com/forums

**Comment by MohsinNadeem** [comment]
Sorry, It was my fault. I realized that I had customized my master layout file. Now I set it to default and it works perfectly.

**Comment by putheakhem** [comment]
@thedevdojo please close this issues due to the problem has been recognized!
