### ISSUE TITLE
Can't create new discussion and can't comment

### ISSUE THREAD

**Issue by rexdarel** [thedevdojo/chatter#131]
Laravel 5.5

I followed the instruction in installing chatter but I escape the php artisan make:auth since I already used it. Successful installation but when I click the new discussion button nothing happens. And I can't comment either because the text area keeps on loading and I can't do anything

**Comment by rexdarel** [comment]
When I tried to inspect the page projects/forums I got bunch of errors on the console

1 Uncaught ReferenceError: $ is not defined
    at tinymce.js:1
Uncaught ReferenceError: $ is not defined
    at forums:256
Uncaught ReferenceError: jQuery is not defined
    at spectrum.js:16
    at spectrum.js:18
Uncaught ReferenceError: $ is not defined
    at chatter.js:1
Uncaught ReferenceError: $ is not defined
    at forums:266

**Comment by shrikanth003** [comment]
I'm receiving the same error. How to fix this?

**Comment by shrikanth003** [comment]
loading app.js first solved the error

**Comment by ikhsanwidi** [comment]
i'm receiving the same error here.

**Comment by officekanev** [comment]
**ghost** I have Laravel 5.6 project , and by default app.js is load first because
 er is find in to <head> tag 

head
    <script src="{{ asset('js/app.js') }}" defer></script>  <-- HERE
    @yield('css')
head
---------------
  and js file is load in to the end of <body> tag but, i 
have same problem
body
    @yield('js')     <-  HERE
body
What exactly do you have in mind, with your comment
 "loading app.js first solved the error"

**Comment by afchodge** [comment]
Has anyone managed to solve this? I am having the same issue.

**Comment by officekanev** [comment]
Yes, just remove  text 'defer' from script tag here 
befor:
<script src="{{ asset('js/app.js') }}" defer></script>
after:
<script src="{{ asset('js/app.js') }}" ></script>


but is recieve new problem,when press button Sign Up conection with controller is fell, and this case for paymant not working,search something different ,just like me

**Comment by afchodge** [comment]
Thanks for the great help.

**Comment by Gugulethu-Nyoni** [comment]
Thanks for the help removing "defer worked

**Comment by zenvikkcode** [comment]
well in Laravel 5.7 ,do as follows....
![yield](https://user-images.githubusercontent.com/44772288/49892822-9677b100-fe52-11e8-9fe2-c726f9e3f35a.PNG)

**Comment by victortigere** [comment]
well in Laravel 5.7 do as follows....
@yield('js')
![image](https://user-images.githubusercontent.com/44772288/49893772-e8b9d180-fe54-11e8-9ac8-23b3f7728ac3.png)
  @yield('css')
![image](https://user-images.githubusercontent.com/44772288/49893867-29194f80-fe55-11e8-9f90-c88e142f9c6c.png)
...add all this in the <head> tag....

**Comment by DanielKLuke** [comment]
I had this problem and saw jquery errors in the console. After adding these links, everything worked.

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
