### ISSUE TITLE
Great Forum

### ISSUE THREAD

**Issue by iiCe89** [thedevdojo/chatter#14]
This is a great forum 
However it really needs to be able to have the ability to edit the Main header / image so it becomes your own & plus i noticed you cant add Category unless you do this via Database which is a pain

**Comment by JayLancaster** [comment]
You can edit the main header image  via the assets in the public/vendor/devdojo folder. 

We are currently trying to make it standard in chatter that there is some API endpoints to manage model resources so that you can code your interface. As per the driver the data is stored in, i certainly think from the database makes it allot more  convenient.

**Comment by tnylea** [comment]
@iiCe89 Thanks for the comment.

I agree that there needs to be some kind of admin functionality. I was thinking about creating a simple admin interface in case you did not create your own. I'll definitely bump this up in the list.

In the meantime. I'm going to be releasing a really kick-ass package called Voyager: https://dribbble.com/shots/2728557-Voyager-The-Missing-Laravel-Admin

And this will seamlessly integrate with Chatter. Hope that helps 👍

**Comment by pamekar** [comment]
> @iiCe89 Thanks for the comment.
> 
> I agree that there needs to be some kind of admin functionality. I was thinking about creating a simple admin interface in case you did not create your own. I'll definitely bump this up in the list.
> 
> In the meantime. I'm going to be releasing a really kick-ass package called Voyager: https://dribbble.com/shots/2728557-Voyager-The-Missing-Laravel-Admin
> 
> And this will seamlessly integrate with Chatter. Hope that helps +1

Please, is there any guide on how to integrate chatter with voyager? Its gonna help much.

Thanks
