### ISSUE TITLE
Javascript tinyMCE in New Discussion error and not show !

### ISSUE THREAD

**Issue by adityardiansyah** [thedevdojo/chatter#143]
I get an error on his javascript chatter

Uncaught TypeError: c is not a constructor at B.init (tinymce.min.js:11) at n. (tinymce.min.js:11) at Array. (tinymce.min.js:4) at n (tinymce.min.js:3) at p (tinymce.min.js:4) at tinymce.min.js:4 at HTMLScriptElement.i (tinymce.min.js:4)

**Comment by marktopper** [comment]
Please update to the latest version, republish the assets and clear your cache.

**Comment by marktopper** [comment]
Closed due to missing response
