### ISSUE TITLE
Can't insert image to posts

### ISSUE THREAD

**Issue by fkv** [thedevdojo/chatter#148]
I want to upload an image to my post, but when I click the Insert Image button, a little box just pops up and there is no way to upload an image. Is there a way to fix this?

![hockey-02](https://user-images.githubusercontent.com/700526/34315594-467336aa-e73f-11e7-92cc-e26ae8fcd84b.png)

**Comment by galdazbiz** [comment]
this is working for me.. it should be another thing, have you done some modifications to the code? In my case for example changing some routes has caused me several errors

**Comment by marktopper** [comment]
Closed due to missing response.
