### ISSUE TITLE
[object HTMLInputElement]

### ISSUE THREAD

**Issue by shrikanth003** [thedevdojo/chatter#149]
I have installed chatter and voyager and both seem to work fine. But when i click on New discussion in the title field it shows [object HTMLInputElement]. I would like to change this placeholder to Enter Title. I have tried multiple ways but no success. Please help me in changing this

**Comment by zigstum** [comment]
home.blade.php (in vendor file if you didnt over-write the views:
(line 134)
```<input type="text" class="form-control" id="title" name="title" placeholder="Type a title" value="{{ old('title') }}" >```
Don't forget to clear compiled views, this was throwing me.

**Comment by shrikanth003** [comment]
I have already tried that. I did over ride the views and then tried too, but no success. I also ran php artisan view:clear but still it shows [object HTMLInputElement]

<input type="text" class="form-control" id="title" name="title" placeholder="Type a title" v-model="title" value="{{ old('title') }}" >

Is there something im doing wrong?

**Comment by zigstum** [comment]
I removed the v-model also (its not in my above code)
I checked without it, and the title fields still works as expected.
