### ISSUE TITLE
How to extend package

### ISSUE THREAD

**Issue by sogeniusio** [thedevdojo/chatter#150]
I'd like to check if a user has a certain attribute enabled in their row in the database before sending the data to the ChatterDiscussionController.

How do I go about doing this without modifying the code in vendor/devdojo/*. I understand this may be outside the realm of an issue but I wanted to also know if there were any special steps I had to take.

**Comment by NathanHeffley** [comment]
Would doing `php artisan vendor:publish` so that you can modify the routes file and create a middleware work?

**Comment by shrikanth003** [comment]
Well, i have copied the views, models, controllers from the vendor to the app directory and modified them to match to the current theme. I have created my own admin panel where i can add chatter categories and posts. It worked! Currently trying to add voting system and social share to the forum.

**Comment by galdazbiz** [comment]
@shrikanth003 Could you please share that? I'm amateur, but one of my problems is that all the code, public etc.. is under vendor, so if some day there's an update, I'll probably have all the code remplaced. I'm trying to isolate this forum into a new folder, outside my laravel app and work with it as a new standalone project linking to de DB. I think is what you did right?

**Comment by hosquiat** [comment]
I know it’s easy to override the views but as far as the logic goes it
works best when run through the package.

**Comment by galdazbiz** [comment]
BTW you can solve your problem with isrole() within the view right?

**Comment by marktopper** [comment]
You are more than welcome to send in a pull request for making it easier to do your modification or within the modification to help others that might wanna achieve the same.
