### ISSUE TITLE
Update, Delete not working.

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/chatter#151]
I recently imported this package to my existing project. And there are some functionalities that are not working. Please suggests fixes.

Issue 1: Areas mentioned in screenshot, not working in home.blade.php

![chat1](https://user-images.githubusercontent.com/18332128/34839929-26d3000a-f725-11e7-9c41-cb3abb33caf2.png)

Issue 2: Update Response button not working.

![chat2](https://user-images.githubusercontent.com/18332128/34839987-5ca10fce-f725-11e7-8c67-fb0af51aa0ac.png)

Issue 3: Delete is also not working.

![chat3](https://user-images.githubusercontent.com/18332128/34840004-6b12be18-f725-11e7-83bc-479fab95cffd.png)

Plz suggest the fixes asap. Thanks

**Comment by galdazbiz** [comment]
this is working for me.. it should be another thing, have you done some modifications to the code? In my case for example changing some routes has caused me several errors

**Comment by MohsinNadeem** [comment]
How it is working in your case? As the update & delete controllers are empty.

**Comment by MohsinNadeem** [comment]
How is it working in your case? As the update & delete controllers are empty.

**Comment by galdazbiz** [comment]
Is it your installation new? or have you modified the code somehow?

**Comment by MohsinNadeem** [comment]
I installed it into an existing project. The only thing modified is some stylesheets for Master file.

**Comment by galdazbiz** [comment]
well, try to delete that, don't put custom css, because I just downloaded and it's working correctly.

**Comment by marktopper** [comment]
Make sure you have the latest assets and the cache is cleared.
