### ISSUE TITLE
In config routes don't put any route with the word "posts" as it will break in so many ways.

### ISSUE THREAD

**Issue by galdazbiz** [thedevdojo/chatter#158]
Just in case it happen to anyone, if you decide to change discussion to posts, please don't do it,I think somewhere is reading the word posts in the url, and that's the reason of malfunction.

> 'routes' => [
>         'home'       => '**posts**',
>         'discussion' => '**posts**',
>         etc

**Comment by marktopper** [comment]
You can't have the same route slug for both `home` and `discussion`.

**Comment by tronne** [comment]
Thanks for the answer, but I was saying in just one, try to put posts in discussion ñs and home in home and you will see

**Comment by marktopper** [comment]
Im not sure I understand what you are saying?

**Comment by tronne** [comment]
Yes, put the word "posts" in the discussion route.
 But well, I think it's add you said, that you cannot repeat routes and
there's already one called posts. But it wouldn't be bad to put in comments

**Comment by marktopper** [comment]
Feel free to send a pull request.
