### ISSUE TITLE
SQL error when activating email notifications

### ISSUE THREAD

**Issue by galdazbiz** [thedevdojo/chatter#160]
Whenever I select notify me I can see this in the console:

SQLSTATE[23000]: Integrity constraint violation: 

> 1062 Duplicate entry '1-3' for key 'PRIMARY' (SQL: insert into `chatter_user_discussion` (`discussion_id`, `user_id`) values (3, 1))

I didn't touch the db, it was directly from the migrations. I did another install and there seems to work, although it's a table inconsistency, I wonder if this is affecting more people.

Not sure how to solve it or it affects, so far I couldn't make working the email notifications

**Comment by marktopper** [comment]
Please share the content of the `chatter_user_discussion` table.

**Comment by tronne** [comment]
The problem is solved in my last pull request, there was a duplicated js
