### ISSUE TITLE
0.2.9 SQL ERROR

### ISSUE THREAD

**Issue by jxlwqq** [thedevdojo/chatter#162]
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'order clause' (SQL: select * from `chatter_post` where `chatter_discussion_id` = 22 and `chatter_post`.`deleted_at` is null order by `` desc limit 10 offset 0)
```
version:0.2.9

**Comment by marktopper** [comment]
Please provide a stacktrace

**Comment by jxlwqq** [comment]
laravel version: 5.5.32
upgrade from 0.2.8 to 0.2.9:
stacktrace info, see the image
<img width="1032" alt="wx20180129-214659 2x" src="https://user-images.githubusercontent.com/2421068/35513506-41290bc6-053e-11e8-93d7-3c10ee570a44.png">

**Comment by jxlwqq** [comment]
by the way, if you want to upgrade from 0.2.8 to 0.2.9, you need to alter some tables add a 'deleted_at'

**Comment by fyroc** [comment]
Also having the same issue.

**Comment by marktopper** [comment]
The configuration has been updated and for some reason doesn't load the `order_by` array from the original configuration for a fallback.
Please update the configuration, let me know if you still have issues after that.

**Comment by marktopper** [comment]
Config: https://github.com/thedevdojo/chatter/blob/master/config/chatter.php#L208

**Comment by fyroc** [comment]
@marktopper After updating the config I am still getting the error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'order clause' (SQL: select * from `chatter_discussion` where `chatter_discussion`.`deleted_at` is null order by `` desc limit 15 offset 0)`

**Comment by marktopper** [comment]
@fyroc, can you please share the following result with me?
Open up tinker `php artisan tinker` and write `config('chatter')`.
Then I can try to see if I can remake the issue with your configuration.

**Comment by jxlwqq** [comment]
@marktopper it works (version 0.2.10), thanks.

**Comment by fyroc** [comment]
I got it to work. It was a caching issue on my local machine. Thanks.
