### ISSUE TITLE
Doesn't work on Laravel Framework 5.5.18

### ISSUE THREAD

**Issue by mailtester3182** [thedevdojo/chatter#169]
Hi,
i have perfom all steps of the installation using the Laravel Framework 5.5.18 and when i put nameofsile.com/forums, it retrun a 404 error page?
how it is handled the /forums route? shall be added into web.php file?
please i need your help!

Thanks by advance

**Comment by galdazbiz** [comment]
please select the correct template in config :)
No need to add anything in web.php, all you need is in config -> chatter.php
