### ISSUE TITLE
There are a problem about css and views

### ISSUE THREAD

**Issue by hsntngr55** [thedevdojo/chatter#171]
https://screenshots.firefox.com/vhjhx82Wo2xEKMPx/forum.app
After installation, my forum looks like creepy :/ I dont know, what is my mistake in here but I did everything as well, Also I puplished package but views didint come up under the resources ?

**Comment by hsntngr55** [comment]
I tried something but still there is some error
https://screenshots.firefox.com/oXYqfpJXAwufljWM/forum.app

**Comment by gerbenjacobs** [comment]
The first screenshot misses the `@yield('css')` (and probably the `js` too).

The second screenshot looks good to me, what error do you see?
