### ISSUE TITLE
How to make chatter's home route the home page of the site?

### ISSUE THREAD

**Issue by gercgl** [thedevdojo/chatter#175]
In the Chatter's configuration there is a list of routes so we can modify its alias. But if I set home route to '/' all other routes are broken.

Thanks

**Comment by marktopper** [comment]
I do not believe this is possible.
However, we are open to pull requests.

**Comment by napestershine** [comment]
@gercgl  you can do that by editing chatter.php from config dir. I did it in my project and it works perfectly. :)

**Comment by gercgl** [comment]
I tried it before. It works while changing "forums" to another word but if I set this route to "/" (slash) all other routes are broken, eg: discussions' routes. does it happen to you too @napestershine?

Thanks @marktopper, @napestershine

**Comment by napestershine** [comment]
@gercgl not at all. Can you show error or some stack trace what are you facing ? I am free for next 3 hours so I can help out you with it.

**Comment by marktopper** [comment]
Closed due to inactivity.
