### ISSUE TITLE
Unable to install trying to get property of non-object

### ISSUE THREAD

**Issue by kalyanlahkar** [thedevdojo/chatter#176]
I am using ubuntu 16.04 with php7.1 and laravel 5.5. I am unable to get chatter working. I tried as was written in the Readme file of the package but getting this error. All the migrations and tables have been created successfully and I used the default auth routes and migrations also. 
![screenshot-2018-2-8 whoops there was an error](https://user-images.githubusercontent.com/7114827/35957826-99f9b39a-0cc3-11e8-818b-2d593d488892.png) . Kindly help me out.

**Comment by nithishm** [comment]
Same with me. I'm guessing the if loop should also check for $slug!=''

**Comment by SirFreud** [comment]
Also experiencing the issue here. Followed installation steps also got same error. Using macOS, PHP 7.1, and Laravel 5.5

![screenshot 2018-02-11 12 58 35](https://user-images.githubusercontent.com/7471649/36077046-4de61d44-0f2b-11e8-9935-2810280ecb43.png)

**Comment by larsbo** [comment]
It seems as there are not all changes in the release. 
I added the last two migrations and updated the ChatterTableSeeder.php with the one from the master branch. This solved the issue for me.

**Comment by marktopper** [comment]
@larsbo, if you believe this is an issue in the release, please do a pull request.
