### ISSUE TITLE
tinymce_placeholder is causing issues with views using tinymce editor

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [thedevdojo/chatter#179]
I'm using chatter version 0.2.13
tinymce_placeholder is causing issues with views using tinymce editor, see image below.
I think the extra , after the trans call and before the . is causing this issue in chatter/src/Lang/en/messages.php

`'tinymce_placeholder' => 'Type Your '.trans('chatter::intro.titles.discussion'),.' Here...',`

![image](https://user-images.githubusercontent.com/19599773/36125645-6d7ffad6-101a-11e8-993a-b219c65d9568.png)

**Comment by gerbenjacobs** [comment]
This is fixed now in 0.2.14

**Comment by SachinPawaskarUNO** [comment]
Thank you. Just tested with the new 0.2.14 update and it now working. Thanks for the quick response.
