### ISSUE TITLE
chatter category dropdown select not displaying categories properly in new discussion using tinymce editor

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [thedevdojo/chatter#180]
I'm using chatter version 0.2.13
chatter category dropdown select not displaying categories properly.
Not sure if anyone else is having this issue.
I'm using the latest version of Google Chrome, Version 64.0.3282.119 (Official Build) (64-bit).

![image](https://user-images.githubusercontent.com/19599773/36126029-48376046-101c-11e8-8326-bcaa21c2f49a.png)

**Comment by marktopper** [comment]
Can someone who has this issue please see if they can do a fix for this?
Cause I cannot trigger this issue.

**Comment by SachinPawaskarUNO** [comment]
@marktopper, Thanks for looking into this. I did some work on it this morning, It is **not an issue with chatter**.
There was a select2 on my side that was causing this issue. 
I'm sure that someone else will run into a similar issue in the future. I will at some point in time dig into why select2 is causing this issue.
I'm closing this issue.
