### ISSUE TITLE
Undefined variable: chatter_errors in view discussion.blade.php

### ISSUE THREAD

**Issue by cristianuibar** [thedevdojo/chatter#186]
After upgrading chatter to latest version I encountered the following error.

I manually fixed it by replacing `@if(Session::has('chatter_alert') && $chatter_errors)` with `@if(Session::has('chatter_alert'))` because I couldn't find any use or instantiation for this var $chatter_errors.

It can be worth it for you guys to investigate this and fix it.

```
[2018-02-15 02:56:48] local.ERROR: Undefined variable: chatter_errors (View: C:\xampp\htdocs\apps\laravel\opt\vendor\devdojo\chatter\src\Views\discussion.blade.php) 
```

**Comment by marktopper** [comment]
Thanks for reporting

**Comment by galdazbiz** [comment]
this was reading the info from config to allow or disallow the display of errors..
