### ISSUE TITLE
Installation doesn't work on Laravel 5.6

### ISSUE THREAD

**Issue by neamtua** [thedevdojo/chatter#187]
Tried to install this package. There was no auto-discovery, nothing. Publishing vendor assets didn't work. Tried just running publish and the package wasn't listed.

Tried clearing config cache, dumping autoload, adding the provider to config. Nothing works.

**Comment by neamtua** [comment]
Tried debugging this a bit. I've tried installing it on a 5.5 project and I saw that it installed a different version than on 5.6.
It installed 0.2.14 on 5.5 and 0.2.7 on 5.6.

Tried specifically to require 0.2.14 on 5.6 and I was met with dependencies issues.

> - devdojo/chatter 0.2.14 requires luketowers/purifier ~3.0 -> satisfiable by luketowers/purifier[3.0.0, 3.0.1, 3.0.2, 3.0.3].
    - luketowers/purifier 3.0.0 requires illuminate/filesystem 5.1.*|5.2.*|5.3.* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - luketowers/purifier 3.0.1 requires illuminate/filesystem 5.1.*|5.2.*|5.3.* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - luketowers/purifier 3.0.2 requires illuminate/filesystem 5.1.*|5.2.*|5.3.*|5.4.* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - luketowers/purifier 3.0.3 requires illuminate/filesystem 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].

**Comment by marktopper** [comment]
I do not believe it supports Laravel 5.6.
We are open to pull requests.

**Comment by gerbenjacobs** [comment]
I tried and created a Laravel 5.6 project from scratch. Then required chatter, it installed v0.2.16 and it's working (apart from the db:seed command). For luketowers/purifier it installed v3.0.4.

But I must say I tried the same thing last week and also couldn't get it to work. The service provider auto discovery didn't work then..

**Comment by neamtua** [comment]
It's because luketowers/purifier was updated to work with Laravel 5.6 yesterday so it fixed this package's dependency. Seems to work for me too now.

**Comment by marktopper** [comment]
Glad you got it solved.
