### ISSUE TITLE
Laravel Spark integration

### ISSUE THREAD

**Issue by scottybo** [thedevdojo/chatter#198]
Attempted to install Chatter on Laravel Spark but I get the error 

`View [layouts.app] not found. (View: /var/www/html/chatter/vendor/devdojo/chatter/src/Views/home.blade.php)`

Any ideas?

**Comment by marktopper** [comment]
You have set the layout view (config `chatter.master_file_extend`) to be `layouts.app`, but without having a `layouts/app.blade.php` view file.
I recommend that you just copy it from Laravel's repository or make your own.
