### ISSUE TITLE
Call to undefined method Indal\Markdown\Parser::convertToHtml()

### ISSUE THREAD

**Issue by Gigamick** [thedevdojo/chatter#230]
This seems to work great until I try to post something or reply to something. Then I get the above error:

Call to undefined method Indal\Markdown\Parser::convertToHtml()

any ideas?

**Comment by codiiv** [comment]
Your stack?

**Comment by Gigamick** [comment]
Sorry I solved this and forgot to come back. I didn't have the relevant categories setup in my DB.
