### ISSUE TITLE
Seems abandoned

### ISSUE THREAD

**Issue by ConsoleTVs** [thedevdojo/chatter#24]
To be honest it seems like this package is abandoned for a long time, lots of PR and issues not even answered...

**Comment by Marascon** [comment]
Been an early adopter of this myself one of the first days it came out, it was abandoned rather quickly (in about a week), best way to continue is to either fork or look for another package.

**Comment by JayLancaster** [comment]
Issues are being answered, but tbh allot of them have been duplicates recently. PR have been slowly adopted though and I hope this changes in the near future. I know that @tnylea  is working on an admin interface at the moment though.

**Comment by ConsoleTVs** [comment]
Its the best forum package and it's abandoned like that, I don't get it

**Comment by tnylea** [comment]
Not abandoned. Just had a lot of stuff to do over the holiday season, but I'm going to be working on this package and merging PR's the last couple weeks of this month and I'll have a bit more time available to dedicate to this package :)

**Comment by ConsoleTVs** [comment]
Gonna do my first PR then, fixed lots of routes
