### ISSUE TITLE
Can't post in Laravel 5.8

### ISSUE THREAD

**Issue by MostafaAttia** [thedevdojo/chatter#240]
Hi, Great package BTW.

deprecated `Illuminate\Events\Dispatcher::fire()` was changed to `dispatch`  in Laravel 5.8 .

So now I can't create a new discussion.

**Comment by ygo93** [comment]
how did you solve it?

**Comment by MostafaAttia** [comment]
@ygo93 See https://github.com/thedevdojo/chatter/pull/241#issue-265009304
