### ISSUE TITLE
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

### ISSUE THREAD

**Issue by ZeoNish** [thedevdojo/chatter#244]
![image](https://user-images.githubusercontent.com/8596319/56429664-69d61900-62cc-11e9-9020-39b2c5b1c0ef.png)
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `chatter_discussion` add constraint `chatter_discussion_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade on update cascade)

Laravel Framework 5.8.13

**Comment by ghost** [comment]
Same issue here

**Comment by ergonomicus** [comment]
My guess is that fields don't match. One is int and another is bigint... User id used to be integer, not anymore...

**Comment by ZeoNish** [comment]
> My guess is that fields don't match. One is int and another is bigint... User id used to be integer, not anymore...

I do everything according to the instructions... and I don't know how to fix it....

**Comment by ZeoNish** [comment]
> Same issue here

Hi man , I found a solution!

`
Schema::create('users', function (Blueprint $table) {
            $table->integer('id')->unsigned()->index();
`

by default
`
Schema::create('users', function (Blueprint $table) {
            $table->bigIncrements('id');
`

I can't tell you how right it is... But so migration pass without mistakes!

**Comment by ZeoNish** [comment]
> Same issue here

I found the solution!!!
The standard value for the Users table!
`$table->bigIncrements('id');`

Need to replace all **increments** on **bigIncrements**
all **integer** on **bigInteger**
In all the migration files in "chatter"!
All of the migrations in the manual!

`php artisan migrate`

![image](https://user-images.githubusercontent.com/8596319/57061756-bd7e3480-6cc6-11e9-91c0-62643afa75a0.png)


ps.
![image](https://user-images.githubusercontent.com/8596319/57061967-85c3bc80-6cc7-11e9-938b-49bce215f074.png)
It's alive!

**Comment by ZeoNish** [comment]
More need fire => dispatch

https://laravel.com/docs/5.8/upgrade
![image](https://user-images.githubusercontent.com/8596319/57079870-f5529f80-6cf9-11e9-990a-a62c33881ba2.png)

![image](https://user-images.githubusercontent.com/8596319/57079835-e4099300-6cf9-11e9-9c50-85858f854436.png)

**Comment by ZeoNish** [comment]
if not work tinyMCE ?
need add lib in folder 
public\vendor\devdojo\chatter\assets\js
![image](https://user-images.githubusercontent.com/8596319/57081200-f20ce300-6cfc-11e9-8890-56ca6e56a6c5.png)

tinymce.min.js ( https://cloud.tinymce.com/5/tinymce.min.js )

![image](https://user-images.githubusercontent.com/8596319/57079971-35b21d80-6cfa-11e9-953c-ead544807408.png)

Add `<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>` in project

**Comment by WooHoo245** [comment]
> > Same issue here
> 
> I found the solution!!!
> The standard value for the Users table!
> `$table->bigIncrements('id');`
> 
> Need to replace all **increments** on **bigIncrements**
> all **integer** on **bigInteger**
> In all the migration files in "chatter"!
> All of the migrations in the manual!
> 
> `php artisan migrate`
> 
> ![image](https://user-images.githubusercontent.com/8596319/57061756-bd7e3480-6cc6-11e9-91c0-62643afa75a0.png)
> 
> ps.
> ![image](https://user-images.githubusercontent.com/8596319/57061967-85c3bc80-6cc7-11e9-938b-49bce215f074.png)
> It's alive!

Can you guide clearly where I can find these files to replace it, please? I just tried replace many files but it's still not working to me :(

**Comment by ZeoNish** [comment]
> > > Same issue here
> > 
> > 
> > I found the solution!!!
> > The standard value for the Users table!
> > `$table->bigIncrements('id');`
> > Need to replace all **increments** on **bigIncrements**
> > all **integer** on **bigInteger**
> > In all the migration files in "chatter"!
> > All of the migrations in the manual!
> > `php artisan migrate`
> > ![image](https://user-images.githubusercontent.com/8596319/57061756-bd7e3480-6cc6-11e9-91c0-62643afa75a0.png)
> > ps.
> > ![image](https://user-images.githubusercontent.com/8596319/57061967-85c3bc80-6cc7-11e9-938b-49bce215f074.png)
> > It's alive!
> 
> Can you guide clearly where I can find these files to replace it, please? I just tried replace many files but it's still not working to me :(

folder migrations

site.ru\database\migrations

**Comment by WooHoo245** [comment]
> > > > Same issue here
> > > 
> > > 
> > > I found the solution!!!
> > > The standard value for the Users table!
> > > `$table->bigIncrements('id');`
> > > Need to replace all **increments** on **bigIncrements**
> > > all **integer** on **bigInteger**
> > > In all the migration files in "chatter"!
> > > All of the migrations in the manual!
> > > `php artisan migrate`
> > > ![image](https://user-images.githubusercontent.com/8596319/57061756-bd7e3480-6cc6-11e9-91c0-62643afa75a0.png)
> > > ps.
> > > ![image](https://user-images.githubusercontent.com/8596319/57061967-85c3bc80-6cc7-11e9-938b-49bce215f074.png)
> > > It's alive!
> > 
> > 
> > Can you guide clearly where I can find these files to replace it, please? I just tried replace many files but it's still not working to me :(
> 
> folder migrations
> 
> site.ru\database\migrations

Yayy, I did it. Thank you very much!

**Comment by quohu2405** [comment]
> > > > Same issue here
> > > 
> > > 
> > > I found the solution!!!
> > > The standard value for the Users table!
> > > `$table->bigIncrements('id');`
> > > Need to replace all **increments** on **bigIncrements**
> > > all **integer** on **bigInteger**
> > > In all the migration files in "chatter"!
> > > All of the migrations in the manual!
> > > `php artisan migrate`
> > > ![image](https://user-images.githubusercontent.com/8596319/57061756-bd7e3480-6cc6-11e9-91c0-62643afa75a0.png)
> > > ps.
> > > ![image](https://user-images.githubusercontent.com/8596319/57061967-85c3bc80-6cc7-11e9-938b-49bce215f074.png)
> > > It's alive!
> > 
> > 
> > Can you guide clearly where I can find these files to replace it, please? I just tried replace many files but it's still not working to me :(
> 
> folder migrations
> 
> site.ru\database\migrations

![Screenshot (66)](https://user-images.githubusercontent.com/54845912/89122586-72b72200-d4f2-11ea-9906-8801f8653d60.png)
Can you help me this case, I did successfully step by step. Unluckily, when I go to link localhost:8000/forums, it displayed this issue so how can I fix it?

**Comment by WooHoo245** [comment]
> > > > Same issue here
> > > 
> > > 
> > > I found the solution!!!
> > > The standard value for the Users table!
> > > `$table->bigIncrements('id');`
> > > Need to replace all **increments** on **bigIncrements**
> > > all **integer** on **bigInteger**
> > > In all the migration files in "chatter"!
> > > All of the migrations in the manual!
> > > `php artisan migrate`
> > > ![image](https://user-images.githubusercontent.com/8596319/57061756-bd7e3480-6cc6-11e9-91c0-62643afa75a0.png)
> > > ps.
> > > ![image](https://user-images.githubusercontent.com/8596319/57061967-85c3bc80-6cc7-11e9-938b-49bce215f074.png)
> > > It's alive!
> > 
> > 
> > Can you guide clearly where I can find these files to replace it, please? I just tried replace many files but it's still not working to me :(
> 
> folder migrations
> 
> site.ru\database\migrations

Hi sir,
Can you direct me where I can find the file "forums" to change interface, please?

**Comment by ZeoNish** [comment]
> > > > > Same issue here
> > > > 
> > > > 
> > > > I found the solution!!!
> > > > The standard value for the Users table!
> > > > `$table->bigIncrements('id');`
> > > > Need to replace all **increments** on **bigIncrements**
> > > > all **integer** on **bigInteger**
> > > > In all the migration files in "chatter"!
> > > > All of the migrations in the manual!
> > > > `php artisan migrate`
> > > > ![image](https://user-images.githubusercontent.com/8596319/57061756-bd7e3480-6cc6-11e9-91c0-62643afa75a0.png)
> > > > ps.
> > > > ![image](https://user-images.githubusercontent.com/8596319/57061967-85c3bc80-6cc7-11e9-938b-49bce215f074.png)
> > > > It's alive!
> > > 
> > > 
> > > Can you guide clearly where I can find these files to replace it, please? I just tried replace many files but it's still not working to me :(
> > 
> > 
> > folder migrations
> > site.ru\database\migrations
> 
> Hi sir,
> Can you direct me where I can find the file "forums" to change interface, please?

vendor folder laravel (find in project folder name DevDojo or Chatter) ...
