### ISSUE TITLE
Deleting main discussion does not delete replies

### ISSUE THREAD

**Issue by ashleybakernz** [thedevdojo/chatter#26]
The title says it all.

**Comment by JayLancaster** [comment]
I noticed this. Will look into it

**Comment by ashleybakernz** [comment]
Awesome.

**Comment by timacdonald** [comment]
hey guys, just made a PR for this, check if this fixes the issue you were experiencing.

https://github.com/thedevdojo/chatter/pull/32

**Comment by marktopper** [comment]
This have been fixed and should be closed
