### ISSUE TITLE
How to add more categories

### ISSUE THREAD

**Issue by Hujjat** [thedevdojo/chatter#27]
Hi, 
Thanks for your great package, I have installed the package and everything is well. How can I add more categories for forum discussions? Is there any simple way or we should add them manually to the database. 

Thank's :)

**Comment by timacdonald** [comment]
Pretty sure manually at the moment. Im in the process of adding a way to do it with ui and will pull request when its ready.

**Comment by Hujjat** [comment]
Hmm, That's going to be cool. :) can't wait to see that. 👍

**Comment by tnylea** [comment]
Yeah, right now the way to do this is in the database, but you can use the Voyager https://github.com/the-control-group/voyager package to easily add new categories :)

**Comment by Gumlokt** [comment]
Adding new categories would be a good feature with only **chatter** pagkage is installed IMHO (I mean without the need to install **voyager**)
