### ISSUE TITLE
JSON only views - using them?

### ISSUE THREAD

**Issue by ghost** [thedevdojo/chatter#28]
Is anyone using the JSON only views? There are no links to them in the app, but they are there. Are they for an API or something? Should we be removing them?

**Comment by timacdonald** [comment]
More specifically...

Controller actions:
- ChatterDiscussionController@index (forums/discussion)
- ChatterPostController@index (forums/posts)

**Comment by marktopper** [comment]
I believe that this is no longer in the codebase.

**Comment by tnylea** [comment]
@ghost, I was going to use these for ajax functionality, but I could remove them until then :)
