### ISSUE TITLE
Wrong Route 

### ISSUE THREAD

**Issue by Ahmed-Jamal** [thedevdojo/chatter#29]
When i used it i have some errors with routing so i edit some route in view to be more dynamic 
in home view 
`
@section(Config::get('chatter.yields.head'))
    <link href="{{url('public/vendor/devdojo/chatter/assets/vendor/spectrum/spectrum.css')}}" rel="stylesheet">
	<link href="{{url('public/vendor/devdojo/chatter/assets/css/chatter.css')}}" rel="stylesheet">
@stop
`

**Comment by Ahmed-Jamal** [comment]
i just add url() to the links and actions for forms

**Comment by marktopper** [comment]
If you believe this is an issue, please make a pull request for the change.
