### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by cfreak** [thedevdojo/chatter#30]
What would be the best way to customize the views of chatter?

Would be nice if you have a short tipp for me

Best Regards
Max

**Comment by timacdonald** [comment]
@cfreak,

What you'll need to do is to create this folder in your project

ROOT/resources/views/vendor/chatter/

Then copy these files into that directory...
https://github.com/thedevdojo/chatter/blob/master/src/Views/discussion.blade.php
https://github.com/thedevdojo/chatter/blob/master/src/Views/home.blade.php

Once you've done that any alterations you make in there will be visible on the front-end.

**Comment by marktopper** [comment]
Should be closed

**Comment by tnylea** [comment]
Thanks guys for helping out with this issue :)
