### ISSUE TITLE
tinymce app/css error loading

### ISSUE THREAD

**Issue by x-iceman** [thedevdojo/chatter#33]
![capture d ecran 4](https://cloud.githubusercontent.com/assets/16476983/20856842/e08f0e8e-b91a-11e6-9dca-87c9605211c6.png)

hi,  i can't load vendor asset file app.css , it required by tinymce , 
i have ingrate js and css in app.layout and , but this plugin file is nested , any solution and thanks.

**Comment by marktopper** [comment]
I believe that the path should be `http://localhost:8000/vendor/devdojo/chatter/assets/css/app.css`.

**Comment by TaylorMilne** [comment]
HI x-iceman. How are you?
Today, I have installed this package.
After vendor publish, you will find that the source and assets files are copied to public folder.
So to load the css file, you should change the css liink from here.
public/vendor/devdojo/chatter/assets/js/tinymce.js

1. content_css: 
2. In function : initailizeNewEditor(id)

there is css link: content_css
add public/ to the path

**Comment by Chinese1904** [comment]
fixed in #77
