### ISSUE TITLE
Name the forums route

### ISSUE THREAD

**Issue by Dsaint109** [thedevdojo/chatter#37]
In my application, i would rather call a route my the name.... cos i have some other functions that depend on having the route named. The "/forums" is not a named route.

**Comment by marktopper** [comment]
Please describe the issue.

**Comment by Dsaint109** [comment]
Im new to github... dont know how to...

**Comment by Dsaint109** [comment]
I found a solution by editing the vendor/devdojo/chatter/src/routes
