### ISSUE TITLE
SQLSTATE[HY000] on migration with sqlite

### ISSUE THREAD

**Issue by rogervila** [thedevdojo/chatter#39]
When I try to run migrations with sqlite I get this message:

```sh
[Illuminate\Database\QueryException]                                                                            
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "chat  
  ter_discussion" add column "slug" varchar not null) 
```

**Comment by rogervila** [comment]
Ok, looks like it's a sqlite behaviour, as [explained here](https://laracasts.com/discuss/channels/general-discussion/migrations-sqlite-general-error-1-cannot-add-a-not-null-column-with-default-value-null).

To use SQLite, a `->default()` property must be added on the migrations that return an error.

**Comment by marktopper** [comment]
I do not think that `slug` is ever meant to have a default value.

**Comment by Kender2** [comment]
Then it should be marked nullable.
`$table->string('slug')->unique()->nullable();`
