### ISSUE TITLE
Installation problem in Laravel 5.3

### ISSUE THREAD

**Issue by tisuchi** [thedevdojo/chatter#4]
I am able to install successfully in laravel 5.3. However, after that, no CSS and JS are working although I copied css and js yield. 

None of the link in example post are working.

**Comment by JayLancaster** [comment]
Its working fine for me. Can you post the code for your app.blade.php?

**Comment by thedevdojo** [comment]
@tisuchi Would you be able to post the code for your app.blade.php that JayLancaster recommended above and I can take a look into it further for you 👍 

Thanks.

**Comment by tnylea** [comment]
Closing issue since no response from @tisuchi, please reopen if the issue still exists :)

Thanks.

**Comment by nanayaw-kirk** [comment]
I have the same Issue
This is the code for my app.blade.php

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title> Open School </title>

    
    @yield('css')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" charset="utf-8">
    
  
</head>
<body>
    @include('partials.navigation')
    @yield('content')

<script type="text/javascript" src="http://localhost/cdn/js/jquery.min.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
@yield('js')
</body>
</html>
`

**Comment by JayLancaster** [comment]
Have you done php artisan vendor:publish?

**Comment by nanayaw-kirk** [comment]
@JayLancaster Yes. I have run php artisan vendor publish but the problem persists. There appears to be no css and js published to the assets directory after running the command

**Comment by JayLancaster** [comment]
So when you run vendor:publish, does it say its been copied to /public/vendor/ etc?

**Comment by JayLancaster** [comment]
Try putting your @yield('css') below you importing your bootstrap. I'm not sure if that could be causing your problem

**Comment by nanayaw-kirk** [comment]
@JayLancaster It was copied to public/vendor/devdojo/chatter/assets/etc
I tried putting the @yield('css') above and below the bootstrap import but it's still not working.

**Comment by nanayaw-kirk** [comment]
After inspecting the page I realised the @yield('css') directive points to http://localhost/vendor/devdojo/chatter/assets/vendor/etc
Instead of http//localhost/project/public/vendor/devdojo/...etc

**Comment by nanayaw-kirk** [comment]
I realised the @yield('css') directive points to http://localhost/vendor/devdojo/chatter/assets/vendor/...etc
instead of 
http://localhost/**projectname**/**public**/vendor/devdojo/chatter/assets/vendor/...etc

**Comment by nanayaw-kirk** [comment]
I also realised all links related to the package are outside of the project root

**Comment by MadMenan** [comment]
HI i also have the same issue. when i create a new discussion error well be arrived.


FatalThrowableError in ChatterBeforeNewDiscussion.php line 26:
Type error: Argument 2 passed to DevDojo\Chatter\Events\ChatterBeforeNewDiscussion::__construct() must be an instance of Illuminate\Support\Facades\Validator, instance of Illuminate\Validation\Validator given, called in /home/menan/www/fourm/vendor/devdojo/chatter/src/Controllers/ChatterDiscussionController.php on line 66

**Comment by ivanovicimihai89** [comment]
i have the same problem on laravel 5.4 

ErrorException in ChatterBeforeNewDiscussion.php line 26:
Argument 2 passed to DevDojo\Chatter\Events\ChatterBeforeNewDiscussion::__construct() must be an instance of Illuminate\Support\Facades\Validator, instance of Illuminate\Validation\Validator given, called in C:\wamp64\www\elearning\vendor\devdojo\chatter\src\Controllers\ChatterDiscussionController.php on line 66 and defined

**Comment by Chinese1904** [comment]
Please manually change these files #80 until it is released
