### ISSUE TITLE
Move views to vendor directory

### ISSUE THREAD

**Issue by rogervila** [thedevdojo/chatter#40]
Hello,

Based on [this issue](https://github.com/thedevdojo/chatter/issues/30), it would be nice if the `ChatterServiceProvider`could copy the views into the `resources/views/vendor` directory. Then, customization would be easier to handle.

If you agree, I can make a PR.

**Comment by marktopper** [comment]
What issue? The link is broken.

**Comment by rogervila** [comment]
@marktopper sorry, I have edited the issue. The link is this one: https://github.com/thedevdojo/chatter/issues/30

**Comment by tnylea** [comment]
Thanks guys, closing this issue :)
