### ISSUE TITLE
*IMPORTANT* Implement the views and answered field in the Chatter_Discussion table and TinyMCE error 

### ISSUE THREAD

**Issue by Dsaint109** [thedevdojo/chatter#41]
I want to be able to notify a user on when there is a comment in his discussion.

**Also**

When I input an image source in the TinyMCE editor, it shows the preview but after posting it doesn't display.

**# WHEN I UPLOAD**

![1](https://cloud.githubusercontent.com/assets/11745653/22017386/72900c9a-dcaa-11e6-8501-65cba0a4ea7c.PNG)

**# AFTER UPLOADING**

![2](https://cloud.githubusercontent.com/assets/11745653/22017427/a80f8bd4-dcaa-11e6-93e8-25ef4c13e2a9.PNG)

**# I CHECK CHROME CONSOLE**
![3](https://cloud.githubusercontent.com/assets/11745653/22017446/c25d201e-dcaa-11e6-95f7-45a9db18f93c.PNG)

# **I EDIT IT FROM THE DISCUSSION**

![4](https://cloud.githubusercontent.com/assets/11745653/22017608/4d040016-dcab-11e6-8b9f-53c6b5a0dec9.PNG)

> Please can you tell me what part of the code to edit to fix this... I can try to find it myself but i still have a lot to do in a short period of time.

Thanks Mate. Good Job.

**Comment by marktopper** [comment]
What is the full URL for the image?

**Comment by Dsaint109** [comment]
It's there

**Comment by marktopper** [comment]
@Dsaint109: Full URL including domain and all that (you may replace domain with `xxx.xxx`).

**Comment by marktopper** [comment]
Closed due to inactivity.

**Comment by Dsaint109** [comment]
I found the solution, Thanks
