### ISSUE TITLE
Utilize Laravel events instead of wordpress style callback functions

### ISSUE THREAD

**Issue by mablae** [thedevdojo/chatter#45]
Just an quick idea I got when I watched @ThomasBS ' stream on 
https://www.liveedu.tv/thomasbs/

Laravel already ships with an event system. The chatter should register events there.

**Comment by Dsaint109** [comment]
Exactly 👍

**Comment by marktopper** [comment]
This would be more suitable as a pull request.

**Comment by ThomasBS** [comment]
@marktopper your wish is my command (#50)

**Comment by marktopper** [comment]
Will try get in touch with @thedevdojo 👍

**Comment by marktopper** [comment]
#50 have been merged.
