### ISSUE TITLE
Config not working as expected

### ISSUE THREAD

**Issue by JayLancaster** [thedevdojo/chatter#5]
I have installed chatter into my project however the config for user profile doesn't work. 
If I have the config set to nothing, it still generates a link to /user

If I add something to the config, it takes no effect.

**Comment by thedevdojo** [comment]
@JayLancaster Thanks for letting me know. Went ahead and pushed an update to version 0.1.22 which should resolve that issue. You should be able to do a simple:

```composer update```

And then check it again.

Keep me posted, but I checked on my end and it all seemed to be working well.

Thanks again.

**Comment by JayLancaster** [comment]
Working perfect. Thanks a ton.
