### ISSUE TITLE
Nothing to migrate.

### ISSUE THREAD

**Issue by ccostel** [thedevdojo/chatter#56]
Hey, 

Thanks for the work on this package. 

I was trying to integrate it with mine but after I do a `php artisan vendor:publish` I do not get any migrations from the package. 

When I run `php artisan migrate` I get `Nothing to migrate.`

I am running Laravel 5.2. 

Is it me doing something wrong? I am supposed to copy and paste the migrations manually?

Thanks!

**Comment by marktopper** [comment]
Add the service provider to your `config/app.php` providers array:
```DevDojo\Chatter\ChatterServiceProvider::class,```

First after this you can run the `php artisan vendor:publish`.

> Please also note that if you have cached the configuration, you might need to clear the cache after modifying the configuration.

**Comment by Moodser** [comment]
I am also facing same issue...
I have follow all steps mentioned but its still saying: Nothing to migrate...
