### ISSUE TITLE
Override Routes

### ISSUE THREAD

**Issue by bonnybakshi** [thedevdojo/chatter#57]
I would like to override some of the routing in my application’s routes folder from this chatter's routes. How do I do that ?

**Comment by marktopper** [comment]
Can you be more specific of what you would like to override?

**Comment by bonnybakshi** [comment]
I am building a search function for the forum. 
I want to add this code in  ChatterController 
`if (isset($slug)) {
            if($slug == ''){
                Session::put('chatterslug', null);
            }else{
              Session::put('chatterslug', $slug);  
            }
            ……….
        }`

I want ‘/forums’  route to point at Chatter controller in my App\Http\Controllers instead of  DevDojo\Chatter\Controllers

**Comment by marktopper** [comment]
You can't dot the Controller class, you will have to do each controller that extends the `Controller` class.

```
Route::get('/chatter', [
    'as'         => 'chatter.home',
    'uses'       => 'ChatterController@index',
    'middleware' => config('chatter.middleware.home'),
]);
```

However, adding a search feature would be more than welcome as a pull request.
