### ISSUE TITLE
New discussion category dropdown

### ISSUE THREAD

**Issue by JayLancaster** [thedevdojo/chatter#6]
I have noticed that on the new discussion popup, We have a big of a bug.
Edit - See comments below a temporary fix has been found

Until the package has been updated, you can fix this temporarily within your chatter by declaring the following CSS in your forum custom stylesheet

```
.col-md-7 .form-control {
    padding: 25px 20px;
}

.col-md-4 .form-control {
    padding: 0 !important;
}
```

Without this you cannot see the currently selected option in the dropdown.

**Comment by JayLancaster** [comment]
I have found the culprit of your weird form issue for the new discussion category dropdown. 
[Image](http://prnt.sc/cg76br)

**Comment by SeanWhelan** [comment]
Had this issue as well, thanks for the solution.

**Comment by JayLancaster** [comment]
no problem :+1:

**Comment by tnylea** [comment]
@JayLancaster Can you submit a pull request for this? If not, I can add it this next week :)

**Comment by JayLancaster** [comment]
I am pretty busy working, but if i get a chance i sure will. If i haven't then ill keep an eye out for the commit, in the mean time the trusty forums.css is winning the day :+1:

**Comment by yash2code** [comment]
@JayLancaster  still the same problem :(

**Comment by SeanWhelan** [comment]
Hey, was this ever fixed? I can submit a pull request right now if it wasn't :)

**Comment by JayLancaster** [comment]
Nah it wasn't fixed yet @SeanWhelan

**Comment by SeanWhelan** [comment]
No problem, submitted a pull request.

**Comment by tnylea** [comment]
Got this one merged and will be tagging a new version within the next 24 hours :)

Thanks.
