### ISSUE TITLE
MarkdownServiceProvider not found on fresh install

### ISSUE THREAD

**Issue by Chinese1904** [thedevdojo/chatter#63]
```
FatalThrowableError in Application.php line 606:
Class 'GrahamCampbell\Markdown\MarkdownServiceProvider' not found
```

because in Chatter's controllers it gets registered:

The `composer.json` needs to be updated with:

```
{
    "require": {
        "graham-campbell/markdown": "^7.0"
    }
}
```

or I prefer checking what the current editor is before registering.

I will send in a PR later.

**Comment by 3309** [comment]
Problem 1
    - Conclusion: don't install graham-campbell/markdown v9.0.0
    - Conclusion: don't install graham-campbell/markdown 9.0.x-dev
    - Conclusion: remove laravel/framework v5.6.3
    - Installation request for graham-campbell/markdown ^9.0 -> satisfiable by graham-campbell/markdown[9.0.x-dev, v9.0.0].
    - Conclusion: don't install laravel/framework v5.6.3
    - graham-campbell/markdown 9.0.x-dev requires illuminate/view 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> satisfiable by illuminate/view[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].

**Comment by BuiltByBucky** [comment]
Same with Laravel 5.7

**Comment by budhaayer** [comment]
Using version ^10.2 for graham-campbell/markdown
./composer.json has been updated


  [Seld\JsonLint\ParsingException]
  "./composer.lock" does not contain valid JSON
  Parse error on line 4540:
  ... }                {
  --------------------^
  Expected one of: 'EOF', '}', ',', ']'


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-depend
encies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>].
..
