### ISSUE TITLE
Upgrading from version 0.1.22

### ISSUE THREAD

**Issue by Dsaint109** [thedevdojo/chatter#68]
When I upgraded from v0.1.22...

Normally when a user isnt logged in and tries to create a new disscussion they are redirected to the login page with ?redirect=Forums.

I have built my app around that so 
Now it doesnt even do anything when the new discussion button is clicked.

is there a way around this.

**Comment by Chinese1904** [comment]
Sorry, I don't understand what your question is. When the "create a new discussion" button is clicked you want them to be forwarded to the login page in case they are not logged in?

**Comment by Dsaint109** [comment]
Yes, exactly..

It should go to login?redirect=Forums

**Comment by Chinese1904** [comment]
This behavior already exists and works just fine. In home.blade.php you can see how the login gets called when the button is pressed if the user is guest/not logged in.

```
$('#new_discussion_btn, #cancel_discussion').click(function(){
	@if(Auth::guest())
		window.location.href = "/{{ Config::get('chatter.routes.home') }}/login";
	@else
		$('#new_discussion').slideDown();
		$('#title').focus();
	@endif
});
```

**Comment by Dsaint109** [comment]
I tried it.... nothing happens

**Comment by Chinese1904** [comment]
do a clean install and it will work. You must have changed something that broke the behavior.
