### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by steffen25** [thedevdojo/chatter#69]
Hi there, I found a XSS vulnerability using your package.

1. Create a new discussion with a title and description.
2. Edit the post content to
`<embed src="data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAwIiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoInN0ZWZmZW4yNSBYU1MiKTs8L3NjcmlwdD48L3N2Zz4=" type="image/svg+xml">`
3. Click the update response button
4. Then once the post has been updated with the content above go to next step
5. Click the edit button and then click the update response button again like the step 3.
6. You can now see a popup box with the message "steffen25 XSS"
You can do more nasty stuff this is just an example :)

I tried to capture it using Gyazo but I only had a few seconds to do it but here you go:
[Preview](https://gyazo.com/2672a2da25ea9a35c0f7751854b28a76)

**Comment by Chinese1904** [comment]
Ew, you got a fix? lol

**Comment by steffen25** [comment]
Im working on it right now hold on 👍

**Comment by steffen25** [comment]
@Chinese1904 Fix: https://github.com/thedevdojo/chatter/pull/70/commits/0eb4031ed632897d7577bedd0c6cfa5e4b885401

**Comment by Chinese1904** [comment]
Great thanks!

**Comment by marktopper** [comment]
Closing this since it's fixed in [`0eb4031`](https://github.com/thedevdojo/chatter/pull/70/commits/0eb4031ed632897d7577bedd0c6cfa5e4b885401).
