### ISSUE TITLE
Use with sentinel

### ISSUE THREAD

**Issue by apatiu** [thedevdojo/chatter#72]
Can I use with sentinel.  I have problem with Auth::user() method

**Comment by Chinese1904** [comment]
I don't think anyone has tested that. Do you use Laravel?

**Comment by apatiu** [comment]
Yes, I use laravel with Sentinel. Now I'm fork this project and modify to use with Seninel. But I'm new to github. I don't know how to use composer to require my fork project to test on my local laravel app for test my chatter code. Can anyone tell me?

**Comment by Chinese1904** [comment]
You dont need to fork this project. Just follow the instructions in the description. 

> cd into your project
> 
> Include the package in your project
> 
> composer require "devdojo/chatter=0.2.*"
> Add the service provider to your config/app.php providers array:
> 
> DevDojo\Chatter\ChatterServiceProvider::class,
> Publish the Vendor Assets files by running:
> 
> php artisan vendor:publish
> Now that we have published a few new files to our application we need to reload them with the following command:
> 
> composer dump-autoload
> Run Your migrations:
> 
> php artisan migrate
> Quick tip: Make sure that you've created a database and added your database credentials in your .env file.
> 
> Lastly, run the seed files to seed your database with a little data:
> 
> php artisan db:seed --class=ChatterTableSeeder
> Inside of your master.blade.php file include a header and footer yield. Inside the head of your master or app.blade.php add the following:
> 
> @yield('css')
> Then, right above the </body> tag of your master file add the following:
> 
> @yield('js')
