### ISSUE TITLE
Editing a post strips the content.

### ISSUE THREAD

**Issue by CodeSkills** [thedevdojo/chatter#87]
When you create new discussion/post you only strip the content for validation. And you insert the unstripped variable to the creation of the object. 

But when you edit and save it. You strip it for both, the validation and also for the update.

This results in that the html tags are not working after you edit a post. Only when you create one.

**Example**
When you create the post with few line breaks...
<img width="391" alt="screen shot 2017-03-17 at 14 37 07" src="https://cloud.githubusercontent.com/assets/3975293/24045402/44fe79ee-0b1f-11e7-8709-5a5372dcf119.png">

And then you only click edit & save...
<img width="301" alt="screen shot 2017-03-17 at 14 37 17" src="https://cloud.githubusercontent.com/assets/3975293/24045403/4501ea98-0b1f-11e7-9fd3-08f14192ae5f.png">

**Comment by Chinese1904** [comment]
I have already submitted a PR, just need to improve a little and then hopefully in the next release it will be included

**Comment by steffen25** [comment]
@Chinese1904 Yes! :)

**Comment by marktopper** [comment]
I believe this have been fixed in a PR.
