### ISSUE TITLE
User data exposed to the public

### ISSUE THREAD

**Issue by steffen25** [thedevdojo/chatter#93]
Data about the user is exposed to the public (no login required)
E.g. 
https://devdojo.com/forums/discussion
https://devdojo.com/forums/posts
the user's email, paypal, etc. depends on the application user model of course. 
Atleast the password isnt showing :)
There is also a thing called leanpub_api_key wonder what that is and if it can be misused somehow :)

This could be scraped by bots and used for spamming and so on.

**Comment by steffen25** [comment]
I just came across this by a site using the package I will see if I can create a fix in the upcoming days.

**Comment by marktopper** [comment]
Closing
Fixed in #94
