### ISSUE TITLE
Create new discussion gives error in 5.4

### ISSUE THREAD

**Issue by napestershine** [thedevdojo/chatter#96]
![image](https://cloud.githubusercontent.com/assets/8603325/24921715/61229364-1f09-11e7-8489-1c31a0daa80b.png)

TIA

**Comment by kocholes** [comment]
This is related with the issue #80. There's a commit that solve this, but not a new release. You can go to 

`vendor/devdojo/chatter/src/Events/ChatterBeforeNew[Discussion|Response].php` 

and replace

 `use Validator`

 with

`use Illuminate\Validation\Validator`

until a new release is pulled

**Comment by napestershine** [comment]
@kocholes  Thank so much
